name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}-frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}-backend

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
      - name: Build and push backend image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:${{ steps.vars.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:latest
      - name: Send SQS Message backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
          IMAGE_NAME: ${{ env.IMAGE_NAME_BACKEND }}
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          aws sqs send-message \
            --queue-url "$SQS_QUEUE_URL" \
            --message-body "{\"ImageName\":\"ghcr.io/${{ env.IMAGE_NAME_BACKEND }}\",\"ImageTag\":\"${{ steps.vars.outputs.tag }}\",\"DeployTimeSeconds\":\"30\"}"
      - name: Build and push frontend image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.vars.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:latest
      - name: Send SQS Message frontend 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
          IMAGE_NAME: ${{ env.IMAGE_NAME_FRONTEND }}
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          aws sqs send-message \
            --queue-url "$SQS_QUEUE_URL" \
            --message-body "{\"ImageName\":\"ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}\",\"ImageTag\":\"${{ steps.vars.outputs.tag }}\",\"DeployTimeSeconds\":\"30\"}"

